server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: excel-sql-api
  main:
    allow-bean-definition-overriding: true
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
  
  # 缓存配置
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
    redis:
      time-to-live: 1h
      cache-null-values: false
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# Excel SQL引擎配置
excel-sql:
  # 文件存储配置
  storage:
    base-path: ./excel-files
    temp-path: ./excel-files/temp
  # 缓存配置
  cache:
    l1-size: 200
    l2-ttl: 3600
  # 索引配置
  index:
    auto-create: true
    rebuild-threshold: 1000
  # 查询配置
  query:
    timeout-seconds: 30
    max-rows: 10000
    batch-size: 1000
    page-size: 1000
    use-cache: true
    cache-ttl: 300

# 日志配置
logging:
  level:
    root: INFO
    com.excel.sql.engine: DEBUG
  file:
    name: logs/excel-sql-api.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true 

# SpringDoc OpenAPI配置
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
  packages-to-scan: com.excel.sql.engine.controller 
